<?php
/**
 * Settings — Reading and writing the password config file.
 *
 * Included by api.php, which defines the constants used here.
 */

defined('TFS_APP') or exit;

function config_load()
{
    if (!file_exists(CONFIG_FILE)) {
        return null;
    }
    $config = include CONFIG_FILE;
    return is_array($config) && !empty($config['password_hash']) ? $config : null;
}

function config_is_set(): bool
{
    return config_load() !== null;
}

/**
 * Deletes the password file, returning the server to its unconfigured state.
 *
 * This does not expose the files: every action still needs a session, and
 * nobody holds one afterwards. It does mean the next visitor can claim the
 * server through the setup screen, so the UI says so before calling this.
 */
function config_clear(): bool
{
    if (!file_exists(CONFIG_FILE)) {
        return true;
    }
    return @unlink(CONFIG_FILE);
}

function config_write(string $passwordHash): bool
{
    $contents = "<?php\n"
        . "// Generated by the Text File Storage setup screen. Keep this file private.\n"
        . "return ['password_hash' => " . var_export($passwordHash, true) . "];\n";

    if (file_put_contents(CONFIG_FILE, $contents, LOCK_EX) === false) {
        return false;
    }
    @chmod(CONFIG_FILE, 0600);
    return true;
}
